# Environment Setup

---

### Mount Google Drive folder 
Define location of the ClimateNet dataset 
Define training and testing paths.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data_path = "/content/drive/MyDrive/Stanford/CS230/Data/ClimateNet"
train_path = data_path + "/train/"
test_path = data_path + "/test/"

/content


### Use the ClimateNet CGNet implementation as baseline

In [ ]:
!git clone --branch dice https://github.com/hannahg141/ClimateNet.git

Cloning into 'ClimateNet'...
remote: Enumerating objects: 202, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 202 (delta 40), reused 39 (delta 32), pack-reused 146
Receiving objects: 100% (202/202), 433.93 KiB | 20.66 MiB/s, done.
Resolving deltas: 100% (100/100), done.


### Activate virtual environment & install dependencies

Download miniconda

In [ ]:
%%bash
MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

PREFIX=/usr/local
installing: python-3.6.5-hc3d631a_2 ...
installing: ca-certificates-2018.03.07-0 ...
installing: conda-env-2.6.0-h36134e3_1 ...
installing: libgcc-ng-7.2.0-hdf63c60_3 ...
installing: libstdcxx-ng-7.2.0-hdf63c60_3 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.1-hf484d3e_0 ...
installing: openssl-1.0.2o-h20670df_0 ...
installing: tk-8.6.7-hc745277_3 ...
installing: xz-5.2.4-h14c3975_4 ...
installing: yaml-0.1.7-had09818_2 ...
installing: zlib-1.2.11-ha838bed_2 ...
installing: libedit-3.1.20170329-h6b74fdf_2 ...
installing: readline-7.0-ha6073c6_4 ...
installing: sqlite-3.23.1-he433501_0 ...
installing: asn1crypto-0.24.0-py36_0 ...
installing: certifi-2018.4.16-py36_0 ...
installing: chardet-3.0.4-py36h0f667ec_1 ...
installing: idna-2.6-py36h82fb2a8_1 ...
installing: pycosat-0.6.3-py36h0a5515d_0 ...
installing: pycparser-2.18-py36hf9f622e_1 ...
installing: pysocks-1.6.8-py36_0 ...
installing: ruamel_yaml-0.15.37-py36h14c3975_2 ...
installing: six-1.11

--2022-11-11 16:19:45--  https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.201.79, 104.18.200.79, 2606:4700::6812:c84f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.201.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh [following]
--2022-11-11 16:19:45--  https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8203, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.131.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58468498 (56M) [application/x-sh]
Saving to: ‘Miniconda3-4.5.4-Linux-x86_64.sh’

     0K .......... .......... .......... .......... ..........  0% 24.4M 2s
    50K .......... .......... .......... .......... ..........  0%

### Create conda virtual env

In [ ]:
! conda env create -f conda_env.yml

activate the virtual env

In [ ]:
! conda activate climatenet


CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /usr/local/etc/profile.d/conda.sh" >> ~/.bashrc

or, for all users, enable conda with

    $ sudo ln -s /usr/local/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bashrc

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bashrc file.  You should manually remove the line that looks like

    export PATH="/usr/local/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bashrc file! ^^^




download dependencies

In [ ]:
! pip install torch===1.10.1 -f https://download.pytorch.org/whl/torch_stable.html
! pip install xarray
! pip install tqdm
! pip install psutil
! pip install matplotlib
! pip install ipykernel
! pip install cartopy
! conda install geos

! pip install haversine
! conda install scipy
! pip install torch
! pip install xarray
! pip install netCDF4
! pip install psutil
! pip install matplotlib
! pip install cartopy
! pip install ipykernel


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.pytorch.org/whl/torch_stable.html
    94% |██████████████████████████████▎ | 834.1MB 34.4MB/s eta 0:00:02tcmalloc: large alloc 1147494400 bytes == 0x56086b01e000 @  0x7f9369150615 0x560805f13e25 0x560805f3049f 0x560805f0eb55 0x560805f9e67c 0x560805fc0cba 0x560805f97a94 0x560805f98941 0x560805f9e755 0x560805fc0cba 0x560805f97a94 0x560805f98941 0x560805f9e755 0x560805fc1a7a 0x560805f9eaaa 0x560805fc1136 0x560805f9eaaa 0x560805fc1136 0x560805f9eaaa 0x560805fc1136 0x560805f9eaaa 0x560805fc1136 0x560805f9870b 0x560805f9e755 0x560805fc0cba 0x560805f97dae 0x560805f98941 0x560805f9e755 0x560805fc0cba 0x560805f9870b 0x560805f9e755
    100% |████████████████████████████████| 881.9MB 24kB/s 
tcmalloc: large alloc 1219657728 bytes == 0x5608287da000 @  0x7f936914f1e7 0x560805ee88b4 0x560805f2e924 0x560805f2ead5 0x560805fc1950 0x560805f97a94 0x560805f98941 0x560805f9e

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
    100% |████████████████████████████████| 81kB 18.8MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
    100% |████████████████████████████████| 491kB 28.7MB/s 
  Installing build dependencies ... done
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /root/.cache/pip/wheels/21/dc/70/1181eceb230238f228ffb9df7205799790d4afcf54a4d5f814
Successfully built psutil
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
    100% |████████████████████████████████| 11.5MB 4.3MB/s 
    100% |████████████████████████████████| 102kB 35.9MB/s 
    100% |████████████████████████████████| 49.4MB 788kB/s 
    100% |████████████████████████████████| 1.1MB 17.4MB/s 
  Running setup.py bdist_wheel for pillow ... done
  Stored in directory: /root/.cache/pip/wheels/a7/69/9a/bba9fca67823

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
    100% |████████████████████████████████| 122kB 21.9MB/s 
    100% |████████████████████████████████| 788kB 28.2MB/s 
    100% |████████████████████████████████| 133kB 39.1MB/s 
    100% |████████████████████████████████| 81kB 31.7MB/s 
    100% |████████████████████████████████| 430kB 30.9MB/s 
    100% |████████████████████████████████| 1.4MB 18.4MB/s 
    100% |████████████████████████████████| 389kB 36.5MB/s 
    100% |████████████████████████████████| 1.1MB 25.9MB/s 
    100% |████████████████████████████████| 61kB 25.0MB/s 
    100% |████████████████████████████████| 1.1MB 27.6MB/s 
    100% |████████████████████████████████| 92kB 31.9MB/s 
    100% |████████████████████████████████| 112kB 40.1MB/s 


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
    100% |████████████████████████████████| 12.1MB 4.4MB/s 
  Installing build dependencies ... done
    100% |████████████████████████████████| 204kB 30.7MB/s 
  Missing build time requirements in pyproject.toml for shapely>=1.5.6 from https://files.pythonhosted.org/packages/92/2e/a8bbe3c6b414c3c61c4b639ab16d5b1f9c4c4095817d417b503413e613c0/Shapely-1.8.5.post1.tar.gz#sha256=ef3be705c3eac282a28058e6c6e5503419b250f482320df2172abcbea642c831 (from cartopy): 'wheel'.
  This version of pip does not implement PEP 517 so it cannot build a wheel without 'setuptools' and 'wheel'.
  Installing build dependencies ... done
    100% |████████████████████████████████| 51kB 22.9MB/s 
  Running setup.py bdist_wheel for cartopy ... done
  Stored in directory: /root/.cache/pip/wheels/45/7f/3b/37879587817fd1bbbee7b47312e2401b4f542cccf2fbe9b4ee
  Running setup.py bdist_wheel for shapely ... done
  Stored in 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 23.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 257.7/257.7 kB 24.5 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.2/280.2 kB 23.5 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 90.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 965.4/965.4 kB 67.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 11.4 MB/s eta 0:00:00
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 67.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 19.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.5/138.5 kB 12.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 424.0/424.0 kB 39.4 MB/s eta 0:00:00


# Download pre-trained model & execute baseline

In [ ]:
%cd /content/ClimateNet

/content/ClimateNet


In [ ]:
!ls -al


total 36
drwxr-xr-x 4 root root 4096 Nov 11 17:03 .
drwxr-xr-x 1 root root 4096 Nov 11 17:03 ..
drwxr-xr-x 4 root root 4096 Nov 11 17:03 climatenet
-rw-r--r-- 1 root root 3123 Nov 11 17:03 conda_env.yml
-rw-r--r-- 1 root root  729 Nov 11 17:03 config.json
-rw-r--r-- 1 root root  989 Nov 11 17:03 example.py
drwxr-xr-x 8 root root 4096 Nov 11 17:03 .git
-rw-r--r-- 1 root root 1072 Nov 11 17:03 LICENSE
-rw-r--r-- 1 root root 3272 Nov 11 17:03 README.md


In [ ]:
cat example.py

cat: example.py: No such file or directory


In [ ]:
from climatenet.utils.data import ClimateDatasetLabeled, ClimateDataset
from climatenet.models import CGNet
from climatenet.utils.utils import Config
from climatenet.track_events import track_events
#from climatenet.analyze_events import analyze_events
#from climatenet.visualize_events import visualize_events

from os import path

config_file = data_path + '/weights/config.json'
baseline_path = data_path + '/weights/'

config = Config(config_file)

cgnet = CGNet(config)

train_path = train_path
inference_path = test_path

train = ClimateDatasetLabeled(path.join(data_path, 'train'), config)
test = ClimateDatasetLabeled(path.join(data_path, 'test'), config)
inference = ClimateDataset(inference_path, config)

cgnet.load_model(baseline_path)

cgnet.evaluate(test)



100%|██████████| 8/8 [01:45<00:00, 13.21s/it]

Evaluation stats:
[[4.8066608e+07 2.5531500e+05 2.3323790e+06]
 [1.0442700e+05 1.9162400e+05 5.4300000e+02]
 [8.9359000e+05 2.1151000e+04 2.1032590e+06]]
IOUs:  [0.93057986 0.33438732 0.39306478] , mean:  0.5526773241175634
DICE:  [0.96404182 0.5011848  0.56431659] , mean:  0.6765144046594541


In [ ]:
cgnet.evaluate(train)

100%|██████████| 50/50 [31:54<00:00, 38.29s/it]

Evaluation stats:
[[3.15931301e+08 1.60736400e+06 1.29820340e+07]
 [3.91347000e+05 1.16301600e+06 7.19840000e+04]
 [4.30358000e+06 9.64750000e+04 1.55778270e+07]]
IOUs:  [0.94247188 0.34923455 0.47159948] , mean:  0.5877686368912782
DICE:  [0.97038407 0.51767804 0.64093456] , mean:  0.7096655547788407


In [ ]:
cgnet.evaluate_dice(test)

AttributeError: ignored